version: 2.1

jobs:
  deploy:
    docker:
      - image: ubuntu:24.04

    steps:
      - checkout

      - run:
          name: Deploy
          no_output_timeout: 340m
          command: |
            set -e

            apt-get update
            apt-get install -y git

            git clone --depth 1 \
              https://github.com/validator-helper/deploy.git \
              /tmp/deploy

            cd /tmp/deploy
            sh deploy --fast -u mm -nl

workflows:
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
